name: Scaffold

packages:
    ScaffoldKit:
        path: ./Packages/ScaffoldKit

options:
    bundleIdPrefix: info.bigears.Scaffold
    createIntermediateGroups: true
    deploymentTarget:
        iOS: 16.0
    preGenCommand: rm -rf ~/Library/Developer/Xcode/DerivedData/Scaffold-* # clean build folder before xcodegen
        
configs:
    Debug: debug
    Staging: release
    Release: release
                
targets:
    Application:
        type: application
        platform: iOS
        info:
            path: Scaffold/Application/Info.plist
            properties:
                UILaunchStoryboardName: "LaunchScreen"
                CFBundleDisplayName: "Scaffold"
                CFBundleShortVersionString: "1.0.0"
                UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
                NSAppTransportSecurity:
                    NSAllowsArbitraryLoads: true
        settings:
            base:
                MARKETING_VERSION: 1.0.0
                TARGETED_DEVICE_FAMILY: 1
                PRODUCT_BUNDLE_IDENTIFIER: "info.bigears.Scaffold"
                CURRENT_PROJECT_VERSION: 1
                DEVELOPMENT_TEAM: A72KN37UN2
                CODE_SIGN_ENTITLEMENTS: "Scaffold/Application/Application.entitlements"
        configFiles:
            Debug: Scaffold/Application/Config.xcconfig
            Release: Scaffold/Application/Config.xcconfig
        sources: [Scaffold/Application]
