name: Scaffold

options:
    bundleIdPrefix: info.bigears.Scaffold
    createIntermediateGroups: true
    deploymentTarget:
        iOS: 16.0
    groupOrdering:
        - pattern: '^.*Scaffold'
          order: [Application, Scenes, ScaffoldUI, ScaffoldKit]
        - pattern: '^.*Scenes$'
          order: [Main, Onboarding, Home]
        - pattern: '^.*Onboarding$'
          order: [Onboarding, Login, SignUp]
        # - pattern: '^.*Features$'
        #   order: [Start, Sign In, Home, Quotes, Quote Detail, Settings]
        
targetTemplates:
    Module:
        type: framework
        platform: iOS
        deploymentTarget: 16.0
        settings:
            base:
                GENERATE_INFOPLIST_FILE: true
                TARGETED_DEVICE_FAMILY: 1
                SUPPORTS_MACCATALYST: false
                
targets:
    Application:
        type: application
        platform: iOS
        info:
            path: Scaffold/Application/Info.plist
            properties:
                UILaunchStoryboardName: "LaunchScreen"
                CFBundleDisplayName: "Scaffold"
                CFBundleShortVersionString: "1.0.0"
                UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
                NSAppTransportSecurity:
                    NSAllowsArbitraryLoads: true
        settings:
            base:
                TARGETED_DEVICE_FAMILY: 1
                PRODUCT_BUNDLE_IDENTIFIER: "info.bigears.Scaffold"
                CURRENT_PROJECT_VERSION: 1
        sources: [Scaffold/Application]
        dependencies:
            - target: Main
        
    ScaffoldUI:
        templates:
            - Module
        sources: [Scaffold/ScaffoldUI]

    Common:
        templates:
            - Module
        sources: [Scaffold/ScaffoldKit/Common]

    # Main
    Main:
        templates:
            - Module
        sources: [Scaffold/Scenes/Main]
        dependencies:
            - target: Onboarding
            - target: Home


    # Onboarding
    Onboarding:
        templates:
            - Module
        sources: [Scaffold/Scenes/Onboarding/Onboarding]
        dependencies:
            - target: Login
            - target: SignUp

    # Onboarding/Login
    Login:
        templates:
            - Module
        sources: [Scaffold/Scenes/Onboarding/Login]
        dependencies:
            - target: ScaffoldUI
            - target: Common

    # Onboarding/SignUp
    SignUp:
        templates:
            - Module
        sources: [Scaffold/Scenes/Onboarding/SignUp]
        dependencies:
            - target: ScaffoldUI
            - target: Common

    # Home
    Home:
        templates:
            - Module
        sources: [Scaffold/Scenes/Home]
        dependencies:
            - target: ScaffoldUI
            - target: Common
        
