name: Scaffold

packages:
    ScaffoldKit:
        path: ./Packages/ScaffoldKit

options:
    bundleIdPrefix: info.bigears.Scaffold
    createIntermediateGroups: true
    deploymentTarget:
        iOS: 16.0
    preGenCommand: rm -rf ~/Library/Developer/Xcode/DerivedData/Scaffold-* # clean build folder before xcodegen
        
configs:
    Debug: debug
    Staging: release
    Release: release
                
targets:
    Application:
        type: application
        platform: iOS
        info:
            path: Scaffold/Application/Info.plist
            properties:
                UILaunchStoryboardName: "LaunchScreen"
                CFBundleDisplayName: "Scaffold"
                CFBundleShortVersionString: "1.0.0"
                UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
                NSAppTransportSecurity:
                    NSAllowsArbitraryLoads: true
        settings:
            base:
                ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
                MARKETING_VERSION: 1.0.0
                TARGETED_DEVICE_FAMILY: 1
                PRODUCT_BUNDLE_IDENTIFIER: "info.bigears.Scaffold"
                CURRENT_PROJECT_VERSION: 1
                DEVELOPMENT_TEAM: A72KN37UN2
                CODE_SIGN_ENTITLEMENTS: "Scaffold/Application/Application.entitlements"
        configFiles:
            Debug: Scaffold/Application/Config.xcconfig
            Release: Scaffold/Application/Config.xcconfig
        sources: [Scaffold/Application]
        dependencies:
          - target: AutoFillTests
            codeSign: false
            embed: true

    AutoFillTests:
        type: app-extension
        platform: iOS
        #dependencies:
        #   - target: Application
        settings:
            INFO_PLIST_FILE: "AutoFillTests/Info.plist"
            base:
                ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
                CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
                CODE_SIGN_ENTITLEMENTS: AutoFillTests/AutoFillTests.entitlements
                CODE_SIGN_IDENTITY: "iPhone Developer"
                CODE_SIGN_STYLE: Automatic
                CURRENT_PROJECT_VERSION: 1
                DEVELOPMENT_TEAM: A72KN37UN2
                ENABLE_USER_SCRIPT_SANDBOXING: YES
                GCC_C_LANGUAGE_STANDARD: gnu17
                GCC_PREPROCESSOR_DEFINITIONS:
                  - "DEBUG=1"
                  - "$(inherited)"
                GENERATE_INFOPLIST_FILE: YES
                INFOPLIST_FILE: AutoFillTests/Info.plist
                INFOPLIST_KEY_CFBundleDisplayName: AutoFillTests
                INFOPLIST_KEY_NSHumanReadableCopyright: ""
                IPHONEOS_DEPLOYMENT_TARGET: 17.0
                LOCALIZATION_PREFERS_STRING_CATALOGS: YES
                MARKETING_VERSION: 1.0.0
                PRODUCT_BUNDLE_IDENTIFIER: info.bigears.Scaffold.AutoFillTests
                PRODUCT_NAME: "$(TARGET_NAME)"
                SKIP_INSTALL: YES
                SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
                SWIFT_EMIT_LOC_STRINGS: YES
                SWIFT_VERSION : 5.0
                TARGETED_DEVICE_FAMILY : "1,2"
        sources: 
            - path: "AutoFillTests"
